/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        // Apple-style dark palette (neutral graphite + blue accent).
        'on-primary-fixed-variant': '#454747',
        'inverse-primary': '#5d5f5f',
        secondary: '#abc7ff',
        'on-secondary': '#002f66',
        'on-error': '#690005',
        'on-secondary-fixed-variant': '#00458f',
        'surface-variant': '#353437',
        'secondary-fixed-dim': '#abc7ff',
        primary: '#d6d6d8',
        'surface-dim': '#131315',
        'tertiary-container': '#e2e2e2',
        'on-tertiary': '#2f3131',
        'surface-container-low': '#1b1b1d',
        'surface-tint': '#c6c6c7',
        'tertiary-fixed-dim': '#c6c6c7',
        'on-primary-fixed': '#1a1c1c',
        'on-tertiary-container': '#636565',
        tertiary: '#d6d6d8',
        'inverse-surface': '#e4e2e4',
        'on-secondary-container': '#fefcff',
        'primary-fixed-dim': '#c6c6c7',
        'surface-container-lowest': '#0e0e10',
        outline: '#8e9192',
        'primary-container': '#0372e4',
        'on-background': '#d0d0d2',
        'outline-variant': '#444748',
        surface: '#131315',
        'surface-container': '#1f1f21',
        'on-surface': '#d0d0d2',
        error: '#ffb4ab',
        'error-container': '#93000a',
        background: '#131315',
        'secondary-fixed': '#d7e2ff',
        'on-tertiary-fixed-variant': '#454747',
        'secondary-container': '#0372e4',
        'surface-bright': '#39393b',
        'on-primary-container': '#ffffff',
        'surface-container-high': '#2a2a2c',
        'inverse-on-surface': '#303032',
        'on-surface-variant': '#c4c7c8',
        'on-error-container': '#ffdad6',
        'tertiary-fixed': '#e2e2e2',
        'surface-container-highest': '#353437',
        'on-tertiary-fixed': '#1a1c1c',
        'on-primary': '#2f3131',
        'on-secondary-fixed': '#001b3f',
        'primary-fixed': '#e2e2e2',
      },
      borderRadius: {
        DEFAULT: '0.375rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'container-max': '1440px',
        'panel-gap': '1px',
        base: '4px',
        md: '16px',
        sm: '8px',
        xs: '4px',
        xl: '32px',
        lg: '24px',
      },
      fontFamily: {
        'headline-md': ['Inter'],
        'code-sm': ['JetBrains Mono'],
        'body-sm': ['Inter'],
        'headline-sm': ['Inter'],
        'display-lg': ['Inter'],
        'label-caps': ['Inter'],
        'body-lg': ['Inter'],
        'code-md': ['JetBrains Mono'],
      },
      fontSize: {
        'headline-md': ['22px', { lineHeight: '28px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'code-sm': ['12px', { lineHeight: '18px', fontWeight: '400' }],
        'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'headline-sm': ['17px', { lineHeight: '24px', letterSpacing: '-0.005em', fontWeight: '600' }],
        'display-lg': ['48px', { lineHeight: '52px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'label-caps': ['11px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '600' }],
        'body-lg': ['16px', { lineHeight: '24px', letterSpacing: '-0.001em', fontWeight: '400' }],
        'code-md': ['14px', { lineHeight: '22px', fontWeight: '400' }],
      },
    },
  },
  plugins: [],
};
