/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        'surface-variant': '#2d3449',
        'surface-container-lowest': '#060e20',
        'inverse-primary': '#00687a',
        'secondary-fixed-dim': '#4edea3',
        background: '#0b1326',
        'inverse-surface': '#dae2fd',
        'surface-container-high': '#222a3d',
        error: '#ffb4ab',
        'tertiary-fixed': '#ffddb8',
        'on-secondary-container': '#00311f',
        'on-secondary-fixed-variant': '#005236',
        'on-background': '#dae2fd',
        'on-tertiary-fixed': '#2a1700',
        'tertiary-container': '#e79400',
        'error-container': '#93000a',
        'secondary-fixed': '#6ffbbe',
        'primary-fixed': '#acedff',
        'inverse-on-surface': '#283044',
        outline: '#869397',
        tertiary: '#ffb95f',
        'on-primary': '#003640',
        secondary: '#4edea3',
        'on-primary-fixed': '#001f26',
        'secondary-container': '#00a572',
        'outline-variant': '#3d494c',
        'surface-container-highest': '#2d3449',
        'on-surface-variant': '#bcc9cd',
        'tertiary-fixed-dim': '#ffb95f',
        surface: '#0b1326',
        'on-tertiary-fixed-variant': '#653e00',
        'on-tertiary': '#472a00',
        'on-secondary-fixed': '#002113',
        primary: '#4cd7f6',
        'on-error-container': '#ffdad6',
        'surface-container-low': '#131b2e',
        'surface-dim': '#0b1326',
        'on-tertiary-container': '#563400',
        'on-surface': '#dae2fd',
        'surface-tint': '#4cd7f6',
        'on-secondary': '#003824',
        'primary-fixed-dim': '#4cd7f6',
        'on-primary-fixed-variant': '#004e5c',
        'on-primary-container': '#00424f',
        'on-error': '#690005',
        'surface-container': '#171f33',
        'primary-container': '#06b6d4',
        'surface-bright': '#31394d',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        'container-max': '1440px',
        'panel-gap': '1px',
        base: '4px',
        md: '16px',
        sm: '8px',
        xs: '4px',
        xl: '32px',
        lg: '24px',
      },
      fontFamily: {
        'headline-md': ['Hanken Grotesk'],
        'code-sm': ['JetBrains Mono'],
        'body-sm': ['Inter'],
        'headline-sm': ['Hanken Grotesk'],
        'display-lg': ['Hanken Grotesk'],
        'label-caps': ['JetBrains Mono'],
        'body-lg': ['Inter'],
        'code-md': ['JetBrains Mono'],
      },
      fontSize: {
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'code-sm': ['12px', { lineHeight: '18px', fontWeight: '400' }],
        'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'headline-sm': ['18px', { lineHeight: '24px', fontWeight: '600' }],
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'label-caps': ['11px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '700' }],
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'code-md': ['14px', { lineHeight: '22px', fontWeight: '400' }],
      },
    },
  },
  plugins: [],
};
